### ISSUE TITLE
1. step - > download raw data from https://files.pushshift.io/reddit

### ISSUE THREAD

**Issue by cherepanovic** [fau-klue/german-reddit-korpus#3]
https://files.pushshift.io/reddit requires login. What needs to be done? Is your corpus not more public available?

**Comment by ausgerechnet** [comment]
We have never distributed the actual data. This repository contains scripts to extract language-specific corpora from the raw data.

Since the publication of our paper, Reddit has changed their TOS. As a result, pushshift data are available for community moderators only.

see e.g. https://www.reddit.com/r/pushshift/comments/14ei799/pushshift_live_again_and_how_moderators_can/
